# -*- coding: utf-8 -*-

import sys
import os
import subprocess

exit_code = subprocess.call(
    ['C:\\Program Files\\Python312\\python.exe', '-W', 'ignore', 'C:\\Users\\PERSONAL\\AppData\\Roaming\\Python\\PYTHON~1\\SITE-P~1\\nuitka\\build\\INLINE~1\\bin\\scons.py', '--quiet', '-f', 'C:\\Users\\PERSONAL\\AppData\\Roaming\\Python\\PYTHON~1\\SITE-P~1\\nuitka\\build\\BACKEN~1.SCO', '--jobs', '8', '--warn=no-deprecated', '--no-site-dir', 'source_dir=.', 'nuitka_python=false', 'debug_mode=false', 'debugger_mode=false', 'python_debug=false', 'module_mode=false', 'full_compat=false', 'experimental=', 'trace_mode=false', 'file_reference_mode=runtime', 'module_count=336', 'result_exe=D:\\Daffa\\Coding Projects\\SimplyElements\\main.dist\\main.exe', 'standalone_mode=true', 'onefile_mode=true', 'onefile_temp_mode=true', 'frozen_modules=155', 'python_sysflag_no_site=true', 'nuitka_src=C:\\Users\\PERSONAL\\AppData\\Roaming\\Python\\PYTHON~1\\SITE-P~1\\nuitka\\build', 'python_version=3.12', 'python_prefix=C:\\Program Files\\Python312', 'debug_modes=', 'no_deployment=', 'console_mode=force', 'noelf_mode=true', 'target_arch=x86_64'],
    env={'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\PERSONAL\\AppData\\Roaming', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'SULFURICACID', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\PERSONAL', 'LOCALAPPDATA': 'C:\\Users\\PERSONAL\\AppData\\Local', 'LOGONSERVER': '\\\\SULFURICACID', 'NUITKA_SITE_FILENAME': '15256:C:\\Program Files\\Python312\\Lib\\site.py', 'NUMBER_OF_PROCESSORS': '8', 'ONEDRIVE': 'C:\\Users\\PERSONAL\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\java8path;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files\\Python312\\Scripts\\;C:\\Program Files\\Python312\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Users\\PERSONAL\\AppData\\Local\\Microsoft\\WindowsApps;', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 140 Stepping 1, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '8c01', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PSMODULEPATH': 'C:\\Users\\PERSONAL\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'PYTHONHASHSEED': '0', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\Windows', 'TEMP': 'C:\\Users\\PERSONAL\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\PERSONAL\\AppData\\Local\\Temp', 'USERDOMAIN': 'SULFURICACID', 'USERDOMAIN_ROAMINGPROFILE': 'SULFURICACID', 'USERNAME': 'PERSONAL', 'USERPROFILE': 'C:\\Users\\PERSONAL', 'WINDIR': 'C:\\Windows', 'WSLENV': 'WT_SESSION:WT_PROFILE_ID:', 'WT_PROFILE_ID': '{61c54bbd-c2c6-5271-96e7-009a87ff44bf}', 'WT_SESSION': '2e9ba1c2-172e-491f-b63a-c0ab51227dbf', 'ZES_ENABLE_SYSMAN': '1', 'NUITKA_PYTHON_EXE_PATH': 'C:\\Program Files\\Python312\\python.exe', 'NUITKA_PACKAGE_DIR': 'C:\\Users\\PERSONAL\\AppData\\Roaming\\Python\\Python312\\site-packages\\nuitka', 'NUITKA_CACHE_DIR_DOWNLOADS': 'C:\\Users\\PERSONAL\\AppData\\Local\\Nuitka\\Nuitka\\Cache\\DOWNLO~1', '_NUITKA_ONEFILE_CHILD_GRACE_TIME_INT': '5000', '_NUITKA_BUILD_DEFINITIONS_CATALOG': '_NUITKA_ONEFILE_CHILD_GRACE_TIME_INT,_NUITKA_BUILD_DEFINITIONS_CATALOG', 'NUITKA_QUIET': '0'},
    shell=False
)